### ISSUE TITLE
Feature Request for dynamic device management

### ISSUE THREAD

**Issue by wfrank2509** [WebThingsIO/webthing-java#44]
Hello ...

Currently in all implementations of the framework the Things are configured via the constructor of the Webthings server. i.e. passing in a SingleThing or MultipleThings.

This means that the server needs to be restarted when changes in the configuration occur. 
I would like to propose to add a way to dynamically add/refresh the configuration to allow dynamic device management.

Are there any reasons for the current implementation or objections?

Greets and thanks,
Wolfgang

**Comment by mrstegeman** [comment]
The reason things currently exist as they do is that, when giving the server a `MultipleThings` object, they are indexed by number. For example, the routes would be:
* `/0` -> First thing
* `/1` -> Second thing
* ...

If the list of things is changed at runtime, the indices may no longer be valid.

The reason for doing it this way, rather than using a unique ID as the route, is that things do not have IDs in the spec. If they did, we could have:
* `/thing-id-X`
* `/thing-id-Y`
* ...

This would make the internal data structure irrelevant, as the routes would never change (i.e. if a thing is deleted from the list).

You may want to follow mozilla-iot/wot#29.

If and when we add unique IDs to the spec, I will be changing all of the webthing libraries to use those rather than numeric indices.
